package shot_boxes.questions;

import javax.swing.Timer;

import knowledge_keepers.KnowledgeKeepers;
import shot_boxes.ShotBoxes;

/**
 * Represents an easy-level question box that appears in the game.
 *
 * <p>{@code EasyQuestions} are generated by low-level knowledge keepers
 * and contain questions that are relatively simple for the player to answer.
 * They reward fewer points compared to medium and hard questions.</p>
 *
 * <p>The object descends from the top of the screen, and players can interact
 * with it to gain points. If it reaches the bottom, it resets automatically.</p>
 *
 * @see Questions
 * @see ShotBoxes
 * @author Ahmet Buğra Ertürk
 * @version 1.0
 */
public class EasyQuestions extends Questions implements ShotBoxes{
	
	/**
     * Constructs an {@code EasyQuestions} object with the given question text and point value.
     *
     * @param question the easy-level question to display
     * @param point    the score value granted when this question is answered
     */
	public EasyQuestions(String question, int point) {
		this.question = question;
		this.point = point;
	}
	
	/**
     * Starts the downward movement of the question box from the specified horizontal position.
     *
     * <p>The question falls downward at the slowest speed ({@code speeds[0]}).
     * If it reaches the bottom of the screen, it resets and is removed from the game area.</p>
     *
     * @param X the X-coordinate from which the question starts descending
     */
	@Override
	public void move(KnowledgeKeepers k, int X) {
		// TODO Auto-generated method stub
		if (!k.hasQuestion) {
			k.hasQuestion = true;
			isMoving = true;
			this.X = X;
			moveTimer = new Timer(25, e -> {
				if (Y<500) {
					Y += speeds[0];}
				else {
					k.hasQuestion = false;
					isMoving = false;
					Y = 60;
					moveTimer.stop();
					}
				});
	        moveTimer.start();
		}
	}

}
