package shot_boxes.questions;

import javax.swing.Timer;

import knowledge_keepers.KnowledgeKeepers;
import shot_boxes.ShotBoxes;

/**
 * Represents a hard-level question box that appears in the game.
 *
 * <p>{@code HardQuestions} are generated by high-level knowledge keepers
 * and contain difficult questions. They reward the highest number of points
 * compared to easy and medium-level questions.</p>
 *
 * <p>The question box moves from the top of the screen toward the bottom at
 * the fastest speed. If it reaches the bottom without interaction, it is reset.</p>
 *
 * @see Questions
 * @see ShotBoxes
 * @author Ahmet Buğra Ertürk
 * @version 1.0
 */
public class HardQuestions extends Questions implements ShotBoxes{
	
	/**
     * Constructs a {@code HardQuestions} object with the given question and point value.
     *
     * @param question the hard-level question to display
     * @param point    the score value granted when this question is answered
     */
	public HardQuestions(String question, int point) {
		this.question = question;
		this.point = point;
	}

	/**
     * Initiates the downward movement of the question box from the specified horizontal position.
     *
     * <p>The question falls at the fastest speed defined in {@code speeds[2]}.
     * If it reaches the bottom of the game screen, it resets and is removed.</p>
     *
     * @param X the X-coordinate from which the question starts descending
     */
	@Override
	public void move(KnowledgeKeepers k, int X) {
		// TODO Auto-generated method stub
		if (!k.hasQuestion) {
			k.hasQuestion = true;
			isMoving = true;
			this.X = X;
			moveTimer = new Timer(25, e -> {
				if (Y<500) {
					Y += speeds[2];}
				else {
					k.hasQuestion = false;
					isMoving = false;
					Y = 60;
					moveTimer.stop();
					}
				});
	        moveTimer.start();
		}
	}

}
